---
- hosts: digitalocean

  tasks:
  - include_vars: ../vars/droplet-details.yml
  - include: ../tasks/digitalocean/deploy-do-keys.yml
  - include: ../tasks/digitalocean/destroy-droplet.yml
  - include: ../tasks/digitalocean/remove-do-keys.yml
